apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: acckrspipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: acckrspipelinesjavascriptdocker 
    spec:
      containers:
        - name: acckrspipelinesjavascriptdocker 
          image: myacckrscontainerregistry.azurecr.io/acckrspipelinesjavascriptdocker
          ports:
          - containerPort: 8080